/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MASTER
 */
public class TelaContratacaoServico extends javax.swing.JFrame {
String getImagemSelecionada;
    /**
     * Creates new form TelaContratacaoServico
     */
    public TelaContratacaoServico() {
        initComponents();
        ImageIcon imcon = new ImageIcon(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getFoto());
                Image imFit = imcon.getImage();                
                Image imgFit = imFit.getScaledInstance(txtFoto.getWidth(), txtFoto.getHeight(), Image.SCALE_SMOOTH);
                txtFoto.setIcon(new ImageIcon(imgFit));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContratacaoServicoWhiteBackground = new javax.swing.JPanel();
        ConfirmacaoServicoText = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        InformacoesPersonalcontratadoText = new javax.swing.JLabel();
        NomePersonalContratacaoTexto = new javax.swing.JLabel();
        EnderecoPersonalContratacaoTexto = new javax.swing.JLabel();
        TelefonePersonalContratacaoTexto = new javax.swing.JLabel();
        SexoPersonalContratacaoTexto = new javax.swing.JLabel();
        IdadePersonalContratacaoTexto = new javax.swing.JLabel();
        ImagemPersonalContratacaoTexto = new javax.swing.JPanel();
        txtFoto = new javax.swing.JLabel();
        InputNomePersonalContratacaoTexto = new javax.swing.JLabel();
        InputEnderecoPersonalContratacaoTexto = new javax.swing.JLabel();
        InputTelefoneContratacaoTexto = new javax.swing.JLabel();
        InputIdadePersonalContratacaoTexto = new javax.swing.JLabel();
        InputSexoPersonalContratacaoTexto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ValorPersonalContratacaoTexto = new javax.swing.JLabel();
        InputValorPersonalContratacaoTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contratar serviço");

        ContratacaoServicoWhiteBackground.setBackground(new java.awt.Color(255, 255, 255));
        ContratacaoServicoWhiteBackground.setMinimumSize(new java.awt.Dimension(600, 500));

        ConfirmacaoServicoText.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        ConfirmacaoServicoText.setText("Você tem certeza de que quer contratar o serviço?");

        btnConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setFont(new java.awt.Font("Century", 0, 13)); // NOI18N
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Century", 0, 13)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        InformacoesPersonalcontratadoText.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        InformacoesPersonalcontratadoText.setText("Informações");

        NomePersonalContratacaoTexto.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        NomePersonalContratacaoTexto.setText("Nome");

        EnderecoPersonalContratacaoTexto.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        EnderecoPersonalContratacaoTexto.setText("Endereço");

        TelefonePersonalContratacaoTexto.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        TelefonePersonalContratacaoTexto.setText("Telefone");

        SexoPersonalContratacaoTexto.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        SexoPersonalContratacaoTexto.setText("Sexo");

        IdadePersonalContratacaoTexto.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        IdadePersonalContratacaoTexto.setText("Idade");

        javax.swing.GroupLayout ImagemPersonalContratacaoTextoLayout = new javax.swing.GroupLayout(ImagemPersonalContratacaoTexto);
        ImagemPersonalContratacaoTexto.setLayout(ImagemPersonalContratacaoTextoLayout);
        ImagemPersonalContratacaoTextoLayout.setHorizontalGroup(
            ImagemPersonalContratacaoTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
        );
        ImagemPersonalContratacaoTextoLayout.setVerticalGroup(
            ImagemPersonalContratacaoTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );

        InputNomePersonalContratacaoTexto.setText("jLabel1");
        InputNomePersonalContratacaoTexto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                InputNomePersonalContratacaoTextoPropertyChange(evt);
            }
        });

        InputEnderecoPersonalContratacaoTexto.setText("jLabel1");
        InputEnderecoPersonalContratacaoTexto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                InputEnderecoPersonalContratacaoTextoPropertyChange(evt);
            }
        });

        InputTelefoneContratacaoTexto.setText("jLabel1");
        InputTelefoneContratacaoTexto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                InputTelefoneContratacaoTextoPropertyChange(evt);
            }
        });

        InputIdadePersonalContratacaoTexto.setText("jLabel1");
        InputIdadePersonalContratacaoTexto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                InputIdadePersonalContratacaoTextoPropertyChange(evt);
            }
        });

        InputSexoPersonalContratacaoTexto.setText("jLabel1");
        InputSexoPersonalContratacaoTexto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                InputSexoPersonalContratacaoTextoPropertyChange(evt);
            }
        });

        ValorPersonalContratacaoTexto.setFont(new java.awt.Font("Century", 1, 13)); // NOI18N
        ValorPersonalContratacaoTexto.setText("Valor do Serviço");

        InputValorPersonalContratacaoTexto.setText("jLabel1");
        InputValorPersonalContratacaoTexto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                InputValorPersonalContratacaoTextoPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout ContratacaoServicoWhiteBackgroundLayout = new javax.swing.GroupLayout(ContratacaoServicoWhiteBackground);
        ContratacaoServicoWhiteBackground.setLayout(ContratacaoServicoWhiteBackgroundLayout);
        ContratacaoServicoWhiteBackgroundLayout.setHorizontalGroup(
            ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EnderecoPersonalContratacaoTexto)
                                .addComponent(TelefonePersonalContratacaoTexto)
                                .addComponent(IdadePersonalContratacaoTexto)
                                .addComponent(ValorPersonalContratacaoTexto)
                                .addComponent(NomePersonalContratacaoTexto))
                            .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                                .addComponent(InformacoesPersonalcontratadoText)
                                .addGap(65, 65, 65)))
                        .addGap(31, 31, 31)
                        .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputValorPersonalContratacaoTexto)
                            .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                                .addComponent(InputIdadePersonalContratacaoTexto)
                                .addGap(60, 60, 60)
                                .addComponent(SexoPersonalContratacaoTexto)
                                .addGap(18, 18, 18)
                                .addComponent(InputSexoPersonalContratacaoTexto))
                            .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputTelefoneContratacaoTexto)
                                    .addComponent(InputEnderecoPersonalContratacaoTexto)
                                    .addComponent(InputNomePersonalContratacaoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addComponent(ImagemPersonalContratacaoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(ConfirmacaoServicoText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(59, 59, 59)
                .addComponent(btnConfirmar)
                .addGap(129, 129, 129))
        );
        ContratacaoServicoWhiteBackgroundLayout.setVerticalGroup(
            ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(InformacoesPersonalcontratadoText)
                        .addGap(39, 39, 39)
                        .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                                .addComponent(NomePersonalContratacaoTexto)
                                .addGap(18, 18, 18)
                                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputEnderecoPersonalContratacaoTexto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EnderecoPersonalContratacaoTexto, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TelefonePersonalContratacaoTexto)
                                    .addComponent(InputTelefoneContratacaoTexto)))
                            .addComponent(InputNomePersonalContratacaoTexto)))
                    .addGroup(ContratacaoServicoWhiteBackgroundLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ImagemPersonalContratacaoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InputIdadePersonalContratacaoTexto)
                        .addComponent(SexoPersonalContratacaoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InputSexoPersonalContratacaoTexto))
                    .addComponent(IdadePersonalContratacaoTexto))
                .addGap(18, 18, 18)
                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ValorPersonalContratacaoTexto)
                    .addComponent(InputValorPersonalContratacaoTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ConfirmacaoServicoText)
                .addGap(45, 45, 45)
                .addGroup(ContratacaoServicoWhiteBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmar)
                    .addComponent(btnCancelar))
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContratacaoServicoWhiteBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContratacaoServicoWhiteBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputValorPersonalContratacaoTextoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InputValorPersonalContratacaoTextoPropertyChange
        // TODO add your handling code here:

        InputValorPersonalContratacaoTexto.setText(Double.toString(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getValorServico()));
    }//GEN-LAST:event_InputValorPersonalContratacaoTextoPropertyChange

    private void InputSexoPersonalContratacaoTextoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InputSexoPersonalContratacaoTextoPropertyChange
        // TODO add your handling code here:

        InputSexoPersonalContratacaoTexto.setText(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getSexo());
    }//GEN-LAST:event_InputSexoPersonalContratacaoTextoPropertyChange

    private void InputIdadePersonalContratacaoTextoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InputIdadePersonalContratacaoTextoPropertyChange
        // TODO add your handling code here:

        InputIdadePersonalContratacaoTexto.setText(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getIdade());
    }//GEN-LAST:event_InputIdadePersonalContratacaoTextoPropertyChange

    private void InputTelefoneContratacaoTextoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InputTelefoneContratacaoTextoPropertyChange
        // TODO add your handling code here:

        InputTelefoneContratacaoTexto.setText(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getTelefone());
    }//GEN-LAST:event_InputTelefoneContratacaoTextoPropertyChange

    private void InputEnderecoPersonalContratacaoTextoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InputEnderecoPersonalContratacaoTextoPropertyChange
        // TODO add your handling code here:

        InputEnderecoPersonalContratacaoTexto.setText(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getEndereco());
    }//GEN-LAST:event_InputEnderecoPersonalContratacaoTextoPropertyChange

    private void InputNomePersonalContratacaoTextoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_InputNomePersonalContratacaoTextoPropertyChange
        // TODO add your handling code here:

        InputNomePersonalContratacaoTexto.setText(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getNome());
    }//GEN-LAST:event_InputNomePersonalContratacaoTextoPropertyChange

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:

        int ans = JOptionPane.showConfirmDialog(null, "Você tem certeza de que quer cancelar esta ação?","Aviso",JOptionPane.YES_NO_OPTION);

        if(ans==0) //o usuario quer cancelar a operacao
        {
            this.setVisible(false);
            new TelaAcaoCliente().setVisible(true);
        }else //o usuario nao quer cancelar a operacao
        {
            this.setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).setSaldo(TelaInicio.cadastrosPersonal.get(TelaAcaoCliente.personalEscolhido).getValorServico());

        this.setVisible(false);
        new ConfirmacaoContratacaoServico().setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaContratacaoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaContratacaoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaContratacaoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaContratacaoServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaContratacaoServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmacaoServicoText;
    private javax.swing.JPanel ContratacaoServicoWhiteBackground;
    private javax.swing.JLabel EnderecoPersonalContratacaoTexto;
    private javax.swing.JLabel IdadePersonalContratacaoTexto;
    private javax.swing.JPanel ImagemPersonalContratacaoTexto;
    private javax.swing.JLabel InformacoesPersonalcontratadoText;
    private javax.swing.JLabel InputEnderecoPersonalContratacaoTexto;
    private javax.swing.JLabel InputIdadePersonalContratacaoTexto;
    private javax.swing.JLabel InputNomePersonalContratacaoTexto;
    private javax.swing.JLabel InputSexoPersonalContratacaoTexto;
    private javax.swing.JLabel InputTelefoneContratacaoTexto;
    private javax.swing.JLabel InputValorPersonalContratacaoTexto;
    private javax.swing.JLabel NomePersonalContratacaoTexto;
    private javax.swing.JLabel SexoPersonalContratacaoTexto;
    private javax.swing.JLabel TelefonePersonalContratacaoTexto;
    private javax.swing.JLabel ValorPersonalContratacaoTexto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txtFoto;
    // End of variables declaration//GEN-END:variables
}
